### ISSUE TITLE
Fix CodeCov badge syntax

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-py#14]
I think it’s using Markdown, while our README is in RST since it’s a Python project.

**Comment by strogonoff** [comment]
@stefanomunarini FWIW this is also a syntax error that prevents PyPI publication, because README contents are used for `long_description` of the package.

**Comment by strogonoff** [comment]
Fixed in https://github.com/relaton/relaton-py/commit/cf155344fe417512eb9de4fba869f099c1697cfd

**Comment by stefanomunarini** [comment]
> Badge image doesn’t link to CodeCov currently. Also, it reports unknown for now.

@strogonoff 

The percentage value is now reported instead of showing unknown. See https://github.com/relaton/relaton-py/commit/a498a299deb0233e36aefbfbd46431d02f0a7274

For the record: the Codecov settings were pointing at the `main` branch, but this project default branch is `master`. Updating the branch of reference required to update the badge URL too.
